
name = "Kpiwidgets"
uuid = "1b08a953-4be3-4667-9a23-5bcc29a65e1e"
authors = ["Andrei Kozik <itspxly@gmail.com>"]
version = "1.0.0"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
